travis:
  secure:
    BINSTAR_TOKEN: Q/yLlE2dVtK9XVxLyRSc1ANZ3WzEHYme5waVKnxZ/RG9x8gy/fdqjtc/L4j7siS4isK8p7nHKmX6+2TJlrMeNvg2P1Li/ZIJi89h2UOanEgHjZtQ19IapdMGvx9esx4qGYv5IS7rRzvFW8mgdExkanc4NCzIfB5+LMSwJ8oCEJhLkqoKRVr1WtRLQn8tq+NUgmzWMLa6y5l+XcbsNGNSX+h6zO7xqvgSYGVPlEQfv1arpegJWcaklxPXpDvQxn+XFEiKlSf7nm7dwMsBCDUUTbY9P7McbgxPtRY7Ssou6gczCqz6TjmAL9MrEla/0tvzzBa7N0CCNie4fuVn0unxEdsJXj++YG7HyycKai74tgfCMlMjYZ7Bij0oI9X3sfwdrg4p3GA91VHyPrtZCBz171xSICP5wrfOOPVz/uGETp1qq1u2LafvDruNg1mYm6oc9fWY2i884V7HgFlncH/ZJvO9SQj/Sb79TITvYfCNzvxeRyEzL4Jp0hfP3wJ7mlFfztjijhekzSo0Qftwf89bs2WCLhQRvv4ioTlhLuFUkgSvRd6jKOw1lSZ0nNo/B+n/IDCD7Ed+9aPJXHbP4eIKHGKtyoUGxx7/2jcikg3UCuYvVhPKKaBI3YBR149ctjMh7+9H9jUeZC4H6kRD8ccuuKsw0HPacG7otZaEpFn/B0U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
